### ISSUE TITLE
Color corrections

### ISSUE THREAD

**Issue by Gabirel** [next-geek/next-geek#53]
## TODO list
- [ ] Colors in the table should get corrected. See **Figure A**.
- [ ] Reference's color is ugly. Fix this. See **Figure B**.
- [ ] End quotes are too dark. Make it colorful. See **Figure C**.

### Figure A
![image](https://user-images.githubusercontent.com/12933851/29132376-92cd4910-7d62-11e7-86c5-22491aed649a.png)

### Figure B
![image](https://user-images.githubusercontent.com/12933851/29132396-a4981288-7d62-11e7-8667-8277949981a3.png)

### Figure C
![image](https://user-images.githubusercontent.com/12933851/29132403-ac5eaa18-7d62-11e7-9586-90f655f26918.png)

**Comment by HanielF** [comment]
## Figure A
I've change the table color. 
I don't know why i cannot upload the screenshots.

open the site below to check it.
[table-demo](https://github.com/HanielF/HanielF.github.io/blob/hexo/source/uploads/Screenshot%20from%202019-03-19%2021-26-16.png)
--------------
## Figure B
same as Figure A
[references-demo](https://github.com/HanielF/HanielF.github.io/blob/hexo/source/uploads/Screenshot%20from%202019-03-19%2020-57-25.png)
-------
## Figure C
The problem is caused by the images themselves. 

Only when the images replaced can you make it colorful.

**Comment by Gabirel** [comment]
Fixed in https://github.com/next-geek/next-geek/commit/0b818ec3822eda762484823f12dc6ea881dbbf31
